/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IChildToken } from "../IChildToken";

export class IChildToken__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IChildToken {
    return new Contract(address, _abi, signerOrProvider) as IChildToken;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "depositData",
        type: "bytes",
      },
    ],
    name: "deposit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
