/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface ChainConstantsInterface extends ethers.utils.Interface {
  functions: {
    "CHILD_CHAIN_ID()": FunctionFragment;
    "CHILD_CHAIN_ID_BYTES()": FunctionFragment;
    "ERC712_VERSION()": FunctionFragment;
    "ROOT_CHAIN_ID()": FunctionFragment;
    "ROOT_CHAIN_ID_BYTES()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "CHILD_CHAIN_ID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CHILD_CHAIN_ID_BYTES",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ERC712_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ROOT_CHAIN_ID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ROOT_CHAIN_ID_BYTES",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "CHILD_CHAIN_ID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CHILD_CHAIN_ID_BYTES",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ERC712_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ROOT_CHAIN_ID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ROOT_CHAIN_ID_BYTES",
    data: BytesLike
  ): Result;

  events: {};
}

export class ChainConstants extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: ChainConstantsInterface;

  functions: {
    CHILD_CHAIN_ID(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "CHILD_CHAIN_ID()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    CHILD_CHAIN_ID_BYTES(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "CHILD_CHAIN_ID_BYTES()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    ERC712_VERSION(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "ERC712_VERSION()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    ROOT_CHAIN_ID(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "ROOT_CHAIN_ID()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    ROOT_CHAIN_ID_BYTES(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "ROOT_CHAIN_ID_BYTES()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;
  };

  CHILD_CHAIN_ID(overrides?: CallOverrides): Promise<BigNumber>;

  "CHILD_CHAIN_ID()"(overrides?: CallOverrides): Promise<BigNumber>;

  CHILD_CHAIN_ID_BYTES(overrides?: CallOverrides): Promise<string>;

  "CHILD_CHAIN_ID_BYTES()"(overrides?: CallOverrides): Promise<string>;

  ERC712_VERSION(overrides?: CallOverrides): Promise<string>;

  "ERC712_VERSION()"(overrides?: CallOverrides): Promise<string>;

  ROOT_CHAIN_ID(overrides?: CallOverrides): Promise<BigNumber>;

  "ROOT_CHAIN_ID()"(overrides?: CallOverrides): Promise<BigNumber>;

  ROOT_CHAIN_ID_BYTES(overrides?: CallOverrides): Promise<string>;

  "ROOT_CHAIN_ID_BYTES()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    CHILD_CHAIN_ID(overrides?: CallOverrides): Promise<BigNumber>;

    "CHILD_CHAIN_ID()"(overrides?: CallOverrides): Promise<BigNumber>;

    CHILD_CHAIN_ID_BYTES(overrides?: CallOverrides): Promise<string>;

    "CHILD_CHAIN_ID_BYTES()"(overrides?: CallOverrides): Promise<string>;

    ERC712_VERSION(overrides?: CallOverrides): Promise<string>;

    "ERC712_VERSION()"(overrides?: CallOverrides): Promise<string>;

    ROOT_CHAIN_ID(overrides?: CallOverrides): Promise<BigNumber>;

    "ROOT_CHAIN_ID()"(overrides?: CallOverrides): Promise<BigNumber>;

    ROOT_CHAIN_ID_BYTES(overrides?: CallOverrides): Promise<string>;

    "ROOT_CHAIN_ID_BYTES()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    CHILD_CHAIN_ID(overrides?: CallOverrides): Promise<BigNumber>;

    "CHILD_CHAIN_ID()"(overrides?: CallOverrides): Promise<BigNumber>;

    CHILD_CHAIN_ID_BYTES(overrides?: CallOverrides): Promise<BigNumber>;

    "CHILD_CHAIN_ID_BYTES()"(overrides?: CallOverrides): Promise<BigNumber>;

    ERC712_VERSION(overrides?: CallOverrides): Promise<BigNumber>;

    "ERC712_VERSION()"(overrides?: CallOverrides): Promise<BigNumber>;

    ROOT_CHAIN_ID(overrides?: CallOverrides): Promise<BigNumber>;

    "ROOT_CHAIN_ID()"(overrides?: CallOverrides): Promise<BigNumber>;

    ROOT_CHAIN_ID_BYTES(overrides?: CallOverrides): Promise<BigNumber>;

    "ROOT_CHAIN_ID_BYTES()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    CHILD_CHAIN_ID(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "CHILD_CHAIN_ID()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    CHILD_CHAIN_ID_BYTES(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "CHILD_CHAIN_ID_BYTES()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ERC712_VERSION(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "ERC712_VERSION()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ROOT_CHAIN_ID(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "ROOT_CHAIN_ID()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    ROOT_CHAIN_ID_BYTES(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "ROOT_CHAIN_ID_BYTES()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
