/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface DaoTicketInterface extends ethers.utils.Interface {
  functions: {
    "abcei51243fdgjkh(bytes)": FunctionFragment;
    "account_info_rotate_tine(uint256)": FunctionFragment;
    "eldddhzr(uint256[])": FunctionFragment;
    "mintToSell9630191(uint256)": FunctionFragment;
    "test266151307()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "abcei51243fdgjkh",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "account_info_rotate_tine",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "eldddhzr",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "mintToSell9630191",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "test266151307",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "abcei51243fdgjkh",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "account_info_rotate_tine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "eldddhzr", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "mintToSell9630191",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "test266151307",
    data: BytesLike
  ): Result;

  events: {
    "randallAteMySandwich_dbohban(uint256,address)": EventFragment;
  };

  getEvent(
    nameOrSignatureOrTopic: "randallAteMySandwich_dbohban"
  ): EventFragment;
}

export class DaoTicket extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: DaoTicketInterface;

  functions: {
    abcei51243fdgjkh(
      nickname: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "abcei51243fdgjkh(bytes)"(
      nickname: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    account_info_rotate_tine(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "account_info_rotate_tine(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    eldddhzr(
      hashs: BigNumberish[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "eldddhzr(uint256[])"(
      hashs: BigNumberish[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    mintToSell9630191(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "mintToSell9630191(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    test266151307(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "test266151307()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;
  };

  abcei51243fdgjkh(
    nickname: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "abcei51243fdgjkh(bytes)"(
    nickname: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  account_info_rotate_tine(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  "account_info_rotate_tine(uint256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  eldddhzr(
    hashs: BigNumberish[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "eldddhzr(uint256[])"(
    hashs: BigNumberish[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  mintToSell9630191(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  "mintToSell9630191(uint256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  test266151307(overrides?: CallOverrides): Promise<BigNumber>;

  "test266151307()"(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    abcei51243fdgjkh(
      nickname: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "abcei51243fdgjkh(bytes)"(
      nickname: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    account_info_rotate_tine(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "account_info_rotate_tine(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    eldddhzr(hashs: BigNumberish[], overrides?: CallOverrides): Promise<void>;

    "eldddhzr(uint256[])"(
      hashs: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    mintToSell9630191(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "mintToSell9630191(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    test266151307(overrides?: CallOverrides): Promise<BigNumber>;

    "test266151307()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {
    randallAteMySandwich_dbohban(undefined: null, undefined: null): EventFilter;
  };

  estimateGas: {
    abcei51243fdgjkh(
      nickname: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "abcei51243fdgjkh(bytes)"(
      nickname: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    account_info_rotate_tine(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "account_info_rotate_tine(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    eldddhzr(hashs: BigNumberish[], overrides?: Overrides): Promise<BigNumber>;

    "eldddhzr(uint256[])"(
      hashs: BigNumberish[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    mintToSell9630191(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "mintToSell9630191(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    test266151307(overrides?: CallOverrides): Promise<BigNumber>;

    "test266151307()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    abcei51243fdgjkh(
      nickname: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "abcei51243fdgjkh(bytes)"(
      nickname: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    account_info_rotate_tine(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "account_info_rotate_tine(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    eldddhzr(
      hashs: BigNumberish[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "eldddhzr(uint256[])"(
      hashs: BigNumberish[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    mintToSell9630191(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "mintToSell9630191(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    test266151307(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "test266151307()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
