/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IChildTokenInterface extends ethers.utils.Interface {
  functions: {
    "deposit(address,bytes)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "deposit",
    values: [string, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;

  events: {};
}

export class IChildToken extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IChildTokenInterface;

  functions: {
    deposit(
      user: string,
      depositData: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "deposit(address,bytes)"(
      user: string,
      depositData: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  deposit(
    user: string,
    depositData: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "deposit(address,bytes)"(
    user: string,
    depositData: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    deposit(
      user: string,
      depositData: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "deposit(address,bytes)"(
      user: string,
      depositData: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    deposit(
      user: string,
      depositData: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "deposit(address,bytes)"(
      user: string,
      depositData: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    deposit(
      user: string,
      depositData: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "deposit(address,bytes)"(
      user: string,
      depositData: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
