/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IDaoTreasuryInterface extends ethers.utils.Interface {
  functions: {
    "DaoSponsor()": FunctionFragment;
    "DaoVault()": FunctionFragment;
    "GAS_ATTR_ID()": FunctionFragment;
    "WEB3DAONFT()": FunctionFragment;
    "WETH()": FunctionFragment;
    "borrowGas(uint256,uint256)": FunctionFragment;
    "burnGas(uint256)": FunctionFragment;
    "buyGas(uint256,uint256)": FunctionFragment;
    "debt()": FunctionFragment;
    "gasAttrPrice()": FunctionFragment;
    "gasTax()": FunctionFragment;
    "holdNFTId()": FunctionFragment;
    "max()": FunctionFragment;
    "maxDebt()": FunctionFragment;
    "mintGas(uint256)": FunctionFragment;
    "onERC721Received(address,address,uint256,bytes)": FunctionFragment;
    "quit(uint256,uint256)": FunctionFragment;
    "returnGas(uint256,uint256)": FunctionFragment;
    "sellGas(uint256,uint256)": FunctionFragment;
    "setDaoSponsor(address)": FunctionFragment;
    "setDaoVault(address)": FunctionFragment;
    "setGasAttrPrice(uint256)": FunctionFragment;
    "setGasTax(uint256)": FunctionFragment;
    "setHoldNFTId(uint256)": FunctionFragment;
    "setMaxDebt(uint256)": FunctionFragment;
    "sponsor(uint256,uint256)": FunctionFragment;
    "transferNFT(address,address,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "DaoSponsor",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "DaoVault", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "GAS_ATTR_ID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "WEB3DAONFT",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "WETH", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "borrowGas",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "burnGas",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "buyGas",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "debt", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "gasAttrPrice",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "gasTax", values?: undefined): string;
  encodeFunctionData(functionFragment: "holdNFTId", values?: undefined): string;
  encodeFunctionData(functionFragment: "max", values?: undefined): string;
  encodeFunctionData(functionFragment: "maxDebt", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "mintGas",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "onERC721Received",
    values: [string, string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "quit",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "returnGas",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "sellGas",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setDaoSponsor",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "setDaoVault", values: [string]): string;
  encodeFunctionData(
    functionFragment: "setGasAttrPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setGasTax",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setHoldNFTId",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxDebt",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "sponsor",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferNFT",
    values: [string, string, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "DaoSponsor", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "DaoVault", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "GAS_ATTR_ID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "WEB3DAONFT", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "WETH", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "borrowGas", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "burnGas", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "buyGas", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "debt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "gasAttrPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "gasTax", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "holdNFTId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "max", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "maxDebt", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mintGas", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "onERC721Received",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "quit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "returnGas", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sellGas", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setDaoSponsor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDaoVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGasAttrPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setGasTax", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setHoldNFTId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setMaxDebt", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sponsor", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferNFT",
    data: BytesLike
  ): Result;

  events: {
    "BurnGas(uint256)": EventFragment;
    "BuyGas(uint256,uint256)": EventFragment;
    "MintGas(uint256)": EventFragment;
    "SellGas(uint256,uint256)": EventFragment;
    "SetDaoSponsor(address)": EventFragment;
    "SetDaoVault(address)": EventFragment;
    "SetGasAttrPrice(uint256)": EventFragment;
    "SetGasTax(uint256)": EventFragment;
    "SetHoldNFTId(uint256)": EventFragment;
    "SetMaxDebt(uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "BurnGas"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BuyGas"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MintGas"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SellGas"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetDaoSponsor"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetDaoVault"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetGasAttrPrice"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetGasTax"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetHoldNFTId"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetMaxDebt"): EventFragment;
}

export class IDaoTreasury extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IDaoTreasuryInterface;

  functions: {
    DaoSponsor(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "DaoSponsor()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    DaoVault(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "DaoVault()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    GAS_ATTR_ID(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "GAS_ATTR_ID()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    WEB3DAONFT(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "WEB3DAONFT()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    WETH(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "WETH()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    borrowGas(
      tokenId: BigNumberish,
      gasAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "borrowGas(uint256,uint256)"(
      tokenId: BigNumberish,
      gasAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    burnGas(
      gasAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "burnGas(uint256)"(
      gasAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    buyGas(
      tokenId: BigNumberish,
      ethAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "buyGas(uint256,uint256)"(
      tokenId: BigNumberish,
      ethAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    debt(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "debt()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    gasAttrPrice(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "gasAttrPrice()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    gasTax(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "gasTax()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    holdNFTId(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "holdNFTId()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    max(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "max()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    maxDebt(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "maxDebt()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    mintGas(
      gasAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "mintGas(uint256)"(
      gasAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    onERC721Received(
      operator: string,
      from: string,
      tokenId: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "onERC721Received(address,address,uint256,bytes)"(
      operator: string,
      from: string,
      tokenId: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    quit(
      tokenId: BigNumberish,
      sponsorAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "quit(uint256,uint256)"(
      tokenId: BigNumberish,
      sponsorAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    returnGas(
      tokenId: BigNumberish,
      gasAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "returnGas(uint256,uint256)"(
      tokenId: BigNumberish,
      gasAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    sellGas(
      tokenId: BigNumberish,
      gasAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "sellGas(uint256,uint256)"(
      tokenId: BigNumberish,
      gasAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setDaoSponsor(
      _DaoSponsor: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setDaoSponsor(address)"(
      _DaoSponsor: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setDaoVault(
      _DaoVault: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setDaoVault(address)"(
      _DaoVault: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setGasAttrPrice(
      _gasAttrPrice: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setGasAttrPrice(uint256)"(
      _gasAttrPrice: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setGasTax(
      _gasTax: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setGasTax(uint256)"(
      _gasTax: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setHoldNFTId(
      _holdNFTId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setHoldNFTId(uint256)"(
      _holdNFTId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setMaxDebt(
      _maxDebt: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setMaxDebt(uint256)"(
      _maxDebt: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    sponsor(
      tokenId: BigNumberish,
      ethAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "sponsor(uint256,uint256)"(
      tokenId: BigNumberish,
      ethAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    transferNFT(
      token: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "transferNFT(address,address,uint256)"(
      token: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  DaoSponsor(overrides?: CallOverrides): Promise<string>;

  "DaoSponsor()"(overrides?: CallOverrides): Promise<string>;

  DaoVault(overrides?: CallOverrides): Promise<string>;

  "DaoVault()"(overrides?: CallOverrides): Promise<string>;

  GAS_ATTR_ID(overrides?: CallOverrides): Promise<BigNumber>;

  "GAS_ATTR_ID()"(overrides?: CallOverrides): Promise<BigNumber>;

  WEB3DAONFT(overrides?: CallOverrides): Promise<string>;

  "WEB3DAONFT()"(overrides?: CallOverrides): Promise<string>;

  WETH(overrides?: CallOverrides): Promise<string>;

  "WETH()"(overrides?: CallOverrides): Promise<string>;

  borrowGas(
    tokenId: BigNumberish,
    gasAmount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "borrowGas(uint256,uint256)"(
    tokenId: BigNumberish,
    gasAmount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  burnGas(
    gasAmount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "burnGas(uint256)"(
    gasAmount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  buyGas(
    tokenId: BigNumberish,
    ethAmount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "buyGas(uint256,uint256)"(
    tokenId: BigNumberish,
    ethAmount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  debt(overrides?: CallOverrides): Promise<BigNumber>;

  "debt()"(overrides?: CallOverrides): Promise<BigNumber>;

  gasAttrPrice(overrides?: CallOverrides): Promise<BigNumber>;

  "gasAttrPrice()"(overrides?: CallOverrides): Promise<BigNumber>;

  gasTax(overrides?: CallOverrides): Promise<BigNumber>;

  "gasTax()"(overrides?: CallOverrides): Promise<BigNumber>;

  holdNFTId(overrides?: CallOverrides): Promise<BigNumber>;

  "holdNFTId()"(overrides?: CallOverrides): Promise<BigNumber>;

  max(overrides?: CallOverrides): Promise<BigNumber>;

  "max()"(overrides?: CallOverrides): Promise<BigNumber>;

  maxDebt(overrides?: CallOverrides): Promise<BigNumber>;

  "maxDebt()"(overrides?: CallOverrides): Promise<BigNumber>;

  mintGas(
    gasAmount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "mintGas(uint256)"(
    gasAmount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  onERC721Received(
    operator: string,
    from: string,
    tokenId: BigNumberish,
    data: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  "onERC721Received(address,address,uint256,bytes)"(
    operator: string,
    from: string,
    tokenId: BigNumberish,
    data: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  quit(
    tokenId: BigNumberish,
    sponsorAmount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "quit(uint256,uint256)"(
    tokenId: BigNumberish,
    sponsorAmount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  returnGas(
    tokenId: BigNumberish,
    gasAmount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "returnGas(uint256,uint256)"(
    tokenId: BigNumberish,
    gasAmount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  sellGas(
    tokenId: BigNumberish,
    gasAmount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "sellGas(uint256,uint256)"(
    tokenId: BigNumberish,
    gasAmount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setDaoSponsor(
    _DaoSponsor: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setDaoSponsor(address)"(
    _DaoSponsor: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setDaoVault(
    _DaoVault: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setDaoVault(address)"(
    _DaoVault: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setGasAttrPrice(
    _gasAttrPrice: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setGasAttrPrice(uint256)"(
    _gasAttrPrice: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setGasTax(
    _gasTax: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setGasTax(uint256)"(
    _gasTax: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setHoldNFTId(
    _holdNFTId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setHoldNFTId(uint256)"(
    _holdNFTId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setMaxDebt(
    _maxDebt: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setMaxDebt(uint256)"(
    _maxDebt: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  sponsor(
    tokenId: BigNumberish,
    ethAmount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "sponsor(uint256,uint256)"(
    tokenId: BigNumberish,
    ethAmount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  transferNFT(
    token: string,
    to: string,
    tokenId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "transferNFT(address,address,uint256)"(
    token: string,
    to: string,
    tokenId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    DaoSponsor(overrides?: CallOverrides): Promise<string>;

    "DaoSponsor()"(overrides?: CallOverrides): Promise<string>;

    DaoVault(overrides?: CallOverrides): Promise<string>;

    "DaoVault()"(overrides?: CallOverrides): Promise<string>;

    GAS_ATTR_ID(overrides?: CallOverrides): Promise<BigNumber>;

    "GAS_ATTR_ID()"(overrides?: CallOverrides): Promise<BigNumber>;

    WEB3DAONFT(overrides?: CallOverrides): Promise<string>;

    "WEB3DAONFT()"(overrides?: CallOverrides): Promise<string>;

    WETH(overrides?: CallOverrides): Promise<string>;

    "WETH()"(overrides?: CallOverrides): Promise<string>;

    borrowGas(
      tokenId: BigNumberish,
      gasAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "borrowGas(uint256,uint256)"(
      tokenId: BigNumberish,
      gasAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    burnGas(gasAmount: BigNumberish, overrides?: CallOverrides): Promise<void>;

    "burnGas(uint256)"(
      gasAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    buyGas(
      tokenId: BigNumberish,
      ethAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "buyGas(uint256,uint256)"(
      tokenId: BigNumberish,
      ethAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    debt(overrides?: CallOverrides): Promise<BigNumber>;

    "debt()"(overrides?: CallOverrides): Promise<BigNumber>;

    gasAttrPrice(overrides?: CallOverrides): Promise<BigNumber>;

    "gasAttrPrice()"(overrides?: CallOverrides): Promise<BigNumber>;

    gasTax(overrides?: CallOverrides): Promise<BigNumber>;

    "gasTax()"(overrides?: CallOverrides): Promise<BigNumber>;

    holdNFTId(overrides?: CallOverrides): Promise<BigNumber>;

    "holdNFTId()"(overrides?: CallOverrides): Promise<BigNumber>;

    max(overrides?: CallOverrides): Promise<BigNumber>;

    "max()"(overrides?: CallOverrides): Promise<BigNumber>;

    maxDebt(overrides?: CallOverrides): Promise<BigNumber>;

    "maxDebt()"(overrides?: CallOverrides): Promise<BigNumber>;

    mintGas(gasAmount: BigNumberish, overrides?: CallOverrides): Promise<void>;

    "mintGas(uint256)"(
      gasAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    onERC721Received(
      operator: string,
      from: string,
      tokenId: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    "onERC721Received(address,address,uint256,bytes)"(
      operator: string,
      from: string,
      tokenId: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    quit(
      tokenId: BigNumberish,
      sponsorAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "quit(uint256,uint256)"(
      tokenId: BigNumberish,
      sponsorAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    returnGas(
      tokenId: BigNumberish,
      gasAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "returnGas(uint256,uint256)"(
      tokenId: BigNumberish,
      gasAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    sellGas(
      tokenId: BigNumberish,
      gasAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "sellGas(uint256,uint256)"(
      tokenId: BigNumberish,
      gasAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setDaoSponsor(
      _DaoSponsor: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setDaoSponsor(address)"(
      _DaoSponsor: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setDaoVault(_DaoVault: string, overrides?: CallOverrides): Promise<void>;

    "setDaoVault(address)"(
      _DaoVault: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setGasAttrPrice(
      _gasAttrPrice: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "setGasAttrPrice(uint256)"(
      _gasAttrPrice: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setGasTax(_gasTax: BigNumberish, overrides?: CallOverrides): Promise<void>;

    "setGasTax(uint256)"(
      _gasTax: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setHoldNFTId(
      _holdNFTId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "setHoldNFTId(uint256)"(
      _holdNFTId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setMaxDebt(
      _maxDebt: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "setMaxDebt(uint256)"(
      _maxDebt: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    sponsor(
      tokenId: BigNumberish,
      ethAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "sponsor(uint256,uint256)"(
      tokenId: BigNumberish,
      ethAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    transferNFT(
      token: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "transferNFT(address,address,uint256)"(
      token: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    BurnGas(gasAmount: null): EventFilter;

    BuyGas(tokenId: null, gasAmount: null): EventFilter;

    MintGas(gasAmount: null): EventFilter;

    SellGas(tokenId: null, gasAmount: null): EventFilter;

    SetDaoSponsor(_DaoSponsor: null): EventFilter;

    SetDaoVault(_DaoVault: null): EventFilter;

    SetGasAttrPrice(_gasAttrPrice: null): EventFilter;

    SetGasTax(_gasTax: null): EventFilter;

    SetHoldNFTId(_holdNFTId: null): EventFilter;

    SetMaxDebt(_maxDebt: null): EventFilter;
  };

  estimateGas: {
    DaoSponsor(overrides?: CallOverrides): Promise<BigNumber>;

    "DaoSponsor()"(overrides?: CallOverrides): Promise<BigNumber>;

    DaoVault(overrides?: CallOverrides): Promise<BigNumber>;

    "DaoVault()"(overrides?: CallOverrides): Promise<BigNumber>;

    GAS_ATTR_ID(overrides?: CallOverrides): Promise<BigNumber>;

    "GAS_ATTR_ID()"(overrides?: CallOverrides): Promise<BigNumber>;

    WEB3DAONFT(overrides?: CallOverrides): Promise<BigNumber>;

    "WEB3DAONFT()"(overrides?: CallOverrides): Promise<BigNumber>;

    WETH(overrides?: CallOverrides): Promise<BigNumber>;

    "WETH()"(overrides?: CallOverrides): Promise<BigNumber>;

    borrowGas(
      tokenId: BigNumberish,
      gasAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "borrowGas(uint256,uint256)"(
      tokenId: BigNumberish,
      gasAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    burnGas(gasAmount: BigNumberish, overrides?: Overrides): Promise<BigNumber>;

    "burnGas(uint256)"(
      gasAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    buyGas(
      tokenId: BigNumberish,
      ethAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "buyGas(uint256,uint256)"(
      tokenId: BigNumberish,
      ethAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    debt(overrides?: CallOverrides): Promise<BigNumber>;

    "debt()"(overrides?: CallOverrides): Promise<BigNumber>;

    gasAttrPrice(overrides?: CallOverrides): Promise<BigNumber>;

    "gasAttrPrice()"(overrides?: CallOverrides): Promise<BigNumber>;

    gasTax(overrides?: CallOverrides): Promise<BigNumber>;

    "gasTax()"(overrides?: CallOverrides): Promise<BigNumber>;

    holdNFTId(overrides?: CallOverrides): Promise<BigNumber>;

    "holdNFTId()"(overrides?: CallOverrides): Promise<BigNumber>;

    max(overrides?: CallOverrides): Promise<BigNumber>;

    "max()"(overrides?: CallOverrides): Promise<BigNumber>;

    maxDebt(overrides?: CallOverrides): Promise<BigNumber>;

    "maxDebt()"(overrides?: CallOverrides): Promise<BigNumber>;

    mintGas(gasAmount: BigNumberish, overrides?: Overrides): Promise<BigNumber>;

    "mintGas(uint256)"(
      gasAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    onERC721Received(
      operator: string,
      from: string,
      tokenId: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "onERC721Received(address,address,uint256,bytes)"(
      operator: string,
      from: string,
      tokenId: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    quit(
      tokenId: BigNumberish,
      sponsorAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "quit(uint256,uint256)"(
      tokenId: BigNumberish,
      sponsorAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    returnGas(
      tokenId: BigNumberish,
      gasAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "returnGas(uint256,uint256)"(
      tokenId: BigNumberish,
      gasAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    sellGas(
      tokenId: BigNumberish,
      gasAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "sellGas(uint256,uint256)"(
      tokenId: BigNumberish,
      gasAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setDaoSponsor(
      _DaoSponsor: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setDaoSponsor(address)"(
      _DaoSponsor: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setDaoVault(_DaoVault: string, overrides?: Overrides): Promise<BigNumber>;

    "setDaoVault(address)"(
      _DaoVault: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setGasAttrPrice(
      _gasAttrPrice: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setGasAttrPrice(uint256)"(
      _gasAttrPrice: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setGasTax(_gasTax: BigNumberish, overrides?: Overrides): Promise<BigNumber>;

    "setGasTax(uint256)"(
      _gasTax: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setHoldNFTId(
      _holdNFTId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setHoldNFTId(uint256)"(
      _holdNFTId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setMaxDebt(
      _maxDebt: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setMaxDebt(uint256)"(
      _maxDebt: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    sponsor(
      tokenId: BigNumberish,
      ethAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "sponsor(uint256,uint256)"(
      tokenId: BigNumberish,
      ethAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    transferNFT(
      token: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "transferNFT(address,address,uint256)"(
      token: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    DaoSponsor(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "DaoSponsor()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    DaoVault(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "DaoVault()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    GAS_ATTR_ID(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "GAS_ATTR_ID()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    WEB3DAONFT(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "WEB3DAONFT()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    WETH(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "WETH()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    borrowGas(
      tokenId: BigNumberish,
      gasAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "borrowGas(uint256,uint256)"(
      tokenId: BigNumberish,
      gasAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    burnGas(
      gasAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "burnGas(uint256)"(
      gasAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    buyGas(
      tokenId: BigNumberish,
      ethAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "buyGas(uint256,uint256)"(
      tokenId: BigNumberish,
      ethAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    debt(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "debt()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    gasAttrPrice(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "gasAttrPrice()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    gasTax(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "gasTax()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    holdNFTId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "holdNFTId()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    max(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "max()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    maxDebt(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "maxDebt()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    mintGas(
      gasAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "mintGas(uint256)"(
      gasAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    onERC721Received(
      operator: string,
      from: string,
      tokenId: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "onERC721Received(address,address,uint256,bytes)"(
      operator: string,
      from: string,
      tokenId: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    quit(
      tokenId: BigNumberish,
      sponsorAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "quit(uint256,uint256)"(
      tokenId: BigNumberish,
      sponsorAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    returnGas(
      tokenId: BigNumberish,
      gasAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "returnGas(uint256,uint256)"(
      tokenId: BigNumberish,
      gasAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    sellGas(
      tokenId: BigNumberish,
      gasAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "sellGas(uint256,uint256)"(
      tokenId: BigNumberish,
      gasAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setDaoSponsor(
      _DaoSponsor: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setDaoSponsor(address)"(
      _DaoSponsor: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setDaoVault(
      _DaoVault: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setDaoVault(address)"(
      _DaoVault: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setGasAttrPrice(
      _gasAttrPrice: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setGasAttrPrice(uint256)"(
      _gasAttrPrice: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setGasTax(
      _gasTax: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setGasTax(uint256)"(
      _gasTax: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setHoldNFTId(
      _holdNFTId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setHoldNFTId(uint256)"(
      _holdNFTId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setMaxDebt(
      _maxDebt: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setMaxDebt(uint256)"(
      _maxDebt: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    sponsor(
      tokenId: BigNumberish,
      ethAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "sponsor(uint256,uint256)"(
      tokenId: BigNumberish,
      ethAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    transferNFT(
      token: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "transferNFT(address,address,uint256)"(
      token: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
