/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface MultiSignInterface extends ethers.utils.Interface {
  functions: {
    "MAX_COMMITEE_COUNT()": FunctionFragment;
    "addCommitee(address)": FunctionFragment;
    "changeRequirement(uint256)": FunctionFragment;
    "commitees(uint256)": FunctionFragment;
    "confirmTransaction(uint256)": FunctionFragment;
    "confirmations(uint256,address)": FunctionFragment;
    "getCommitees()": FunctionFragment;
    "getConfirmationCount(uint256)": FunctionFragment;
    "getConfirmations(uint256)": FunctionFragment;
    "isCommitee(address)": FunctionFragment;
    "isConfirmed(uint256)": FunctionFragment;
    "removeCommitee(address)": FunctionFragment;
    "replaceCommitee(address,address)": FunctionFragment;
    "required()": FunctionFragment;
    "revokeConfirmation(uint256)": FunctionFragment;
    "submitTransaction(address,bytes)": FunctionFragment;
    "transactionCount()": FunctionFragment;
    "transactions(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "MAX_COMMITEE_COUNT",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "addCommitee", values: [string]): string;
  encodeFunctionData(
    functionFragment: "changeRequirement",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "commitees",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confirmTransaction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confirmations",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getCommitees",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getConfirmationCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getConfirmations",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "isCommitee", values: [string]): string;
  encodeFunctionData(
    functionFragment: "isConfirmed",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeCommitee",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "replaceCommitee",
    values: [string, string]
  ): string;
  encodeFunctionData(functionFragment: "required", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "revokeConfirmation",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitTransaction",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transactionCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transactions",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "MAX_COMMITEE_COUNT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addCommitee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeRequirement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "commitees", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "confirmTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confirmations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCommitees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getConfirmationCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getConfirmations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isCommitee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isConfirmed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeCommitee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "replaceCommitee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "required", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "revokeConfirmation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transactionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transactions",
    data: BytesLike
  ): Result;

  events: {
    "CommiteeAddition(address)": EventFragment;
    "CommiteeRemoval(address)": EventFragment;
    "Confirmation(address,uint256)": EventFragment;
    "Execution(uint256)": EventFragment;
    "ExecutionFailure(uint256)": EventFragment;
    "ExecutionSuccess(uint256)": EventFragment;
    "RequirementChange(uint256)": EventFragment;
    "Revocation(address,uint256)": EventFragment;
    "Submission(uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CommiteeAddition"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CommiteeRemoval"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Confirmation"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Execution"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ExecutionFailure"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ExecutionSuccess"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RequirementChange"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Revocation"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Submission"): EventFragment;
}

export class MultiSign extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: MultiSignInterface;

  functions: {
    MAX_COMMITEE_COUNT(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "MAX_COMMITEE_COUNT()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    addCommitee(
      commitee: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "addCommitee(address)"(
      commitee: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    changeRequirement(
      _required: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "changeRequirement(uint256)"(
      _required: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    commitees(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "commitees(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    confirmTransaction(
      transactionId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "confirmTransaction(uint256)"(
      transactionId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    confirmations(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    "confirmations(uint256,address)"(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    getCommitees(overrides?: CallOverrides): Promise<{
      0: string[];
    }>;

    "getCommitees()"(overrides?: CallOverrides): Promise<{
      0: string[];
    }>;

    getConfirmationCount(
      transactionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      count: BigNumber;
      0: BigNumber;
    }>;

    "getConfirmationCount(uint256)"(
      transactionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      count: BigNumber;
      0: BigNumber;
    }>;

    getConfirmations(
      transactionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      _confirmations: string[];
      0: string[];
    }>;

    "getConfirmations(uint256)"(
      transactionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      _confirmations: string[];
      0: string[];
    }>;

    isCommitee(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    "isCommitee(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    isConfirmed(
      transactionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      ret: boolean;
      0: boolean;
    }>;

    "isConfirmed(uint256)"(
      transactionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      ret: boolean;
      0: boolean;
    }>;

    removeCommitee(
      commitee: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "removeCommitee(address)"(
      commitee: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    replaceCommitee(
      commitee: string,
      newCommitee: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "replaceCommitee(address,address)"(
      commitee: string,
      newCommitee: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    required(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "required()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    revokeConfirmation(
      transactionId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "revokeConfirmation(uint256)"(
      transactionId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    submitTransaction(
      destination: string,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "submitTransaction(address,bytes)"(
      destination: string,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    transactionCount(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "transactionCount()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    transactions(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      destination: string;
      data: string;
      executed: boolean;
      0: string;
      1: string;
      2: boolean;
    }>;

    "transactions(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      destination: string;
      data: string;
      executed: boolean;
      0: string;
      1: string;
      2: boolean;
    }>;
  };

  MAX_COMMITEE_COUNT(overrides?: CallOverrides): Promise<BigNumber>;

  "MAX_COMMITEE_COUNT()"(overrides?: CallOverrides): Promise<BigNumber>;

  addCommitee(
    commitee: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "addCommitee(address)"(
    commitee: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  changeRequirement(
    _required: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "changeRequirement(uint256)"(
    _required: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  commitees(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  "commitees(uint256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  confirmTransaction(
    transactionId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "confirmTransaction(uint256)"(
    transactionId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  confirmations(
    arg0: BigNumberish,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "confirmations(uint256,address)"(
    arg0: BigNumberish,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  getCommitees(overrides?: CallOverrides): Promise<string[]>;

  "getCommitees()"(overrides?: CallOverrides): Promise<string[]>;

  getConfirmationCount(
    transactionId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getConfirmationCount(uint256)"(
    transactionId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getConfirmations(
    transactionId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string[]>;

  "getConfirmations(uint256)"(
    transactionId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string[]>;

  isCommitee(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  "isCommitee(address)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isConfirmed(
    transactionId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "isConfirmed(uint256)"(
    transactionId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  removeCommitee(
    commitee: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "removeCommitee(address)"(
    commitee: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  replaceCommitee(
    commitee: string,
    newCommitee: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "replaceCommitee(address,address)"(
    commitee: string,
    newCommitee: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  required(overrides?: CallOverrides): Promise<BigNumber>;

  "required()"(overrides?: CallOverrides): Promise<BigNumber>;

  revokeConfirmation(
    transactionId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "revokeConfirmation(uint256)"(
    transactionId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  submitTransaction(
    destination: string,
    data: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "submitTransaction(address,bytes)"(
    destination: string,
    data: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  transactionCount(overrides?: CallOverrides): Promise<BigNumber>;

  "transactionCount()"(overrides?: CallOverrides): Promise<BigNumber>;

  transactions(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<{
    destination: string;
    data: string;
    executed: boolean;
    0: string;
    1: string;
    2: boolean;
  }>;

  "transactions(uint256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<{
    destination: string;
    data: string;
    executed: boolean;
    0: string;
    1: string;
    2: boolean;
  }>;

  callStatic: {
    MAX_COMMITEE_COUNT(overrides?: CallOverrides): Promise<BigNumber>;

    "MAX_COMMITEE_COUNT()"(overrides?: CallOverrides): Promise<BigNumber>;

    addCommitee(commitee: string, overrides?: CallOverrides): Promise<void>;

    "addCommitee(address)"(
      commitee: string,
      overrides?: CallOverrides
    ): Promise<void>;

    changeRequirement(
      _required: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "changeRequirement(uint256)"(
      _required: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    commitees(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    "commitees(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    confirmTransaction(
      transactionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "confirmTransaction(uint256)"(
      transactionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    confirmations(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "confirmations(uint256,address)"(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    getCommitees(overrides?: CallOverrides): Promise<string[]>;

    "getCommitees()"(overrides?: CallOverrides): Promise<string[]>;

    getConfirmationCount(
      transactionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getConfirmationCount(uint256)"(
      transactionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getConfirmations(
      transactionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string[]>;

    "getConfirmations(uint256)"(
      transactionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string[]>;

    isCommitee(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    "isCommitee(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isConfirmed(
      transactionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "isConfirmed(uint256)"(
      transactionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    removeCommitee(commitee: string, overrides?: CallOverrides): Promise<void>;

    "removeCommitee(address)"(
      commitee: string,
      overrides?: CallOverrides
    ): Promise<void>;

    replaceCommitee(
      commitee: string,
      newCommitee: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "replaceCommitee(address,address)"(
      commitee: string,
      newCommitee: string,
      overrides?: CallOverrides
    ): Promise<void>;

    required(overrides?: CallOverrides): Promise<BigNumber>;

    "required()"(overrides?: CallOverrides): Promise<BigNumber>;

    revokeConfirmation(
      transactionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "revokeConfirmation(uint256)"(
      transactionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    submitTransaction(
      destination: string,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "submitTransaction(address,bytes)"(
      destination: string,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transactionCount(overrides?: CallOverrides): Promise<BigNumber>;

    "transactionCount()"(overrides?: CallOverrides): Promise<BigNumber>;

    transactions(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      destination: string;
      data: string;
      executed: boolean;
      0: string;
      1: string;
      2: boolean;
    }>;

    "transactions(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      destination: string;
      data: string;
      executed: boolean;
      0: string;
      1: string;
      2: boolean;
    }>;
  };

  filters: {
    CommiteeAddition(commitee: string | null): EventFilter;

    CommiteeRemoval(commitee: string | null): EventFilter;

    Confirmation(
      sender: string | null,
      transactionId: BigNumberish | null
    ): EventFilter;

    Execution(transactionId: BigNumberish | null): EventFilter;

    ExecutionFailure(transactionId: BigNumberish | null): EventFilter;

    ExecutionSuccess(transactionId: BigNumberish | null): EventFilter;

    RequirementChange(required: null): EventFilter;

    Revocation(
      sender: string | null,
      transactionId: BigNumberish | null
    ): EventFilter;

    Submission(transactionId: BigNumberish | null): EventFilter;
  };

  estimateGas: {
    MAX_COMMITEE_COUNT(overrides?: CallOverrides): Promise<BigNumber>;

    "MAX_COMMITEE_COUNT()"(overrides?: CallOverrides): Promise<BigNumber>;

    addCommitee(commitee: string, overrides?: Overrides): Promise<BigNumber>;

    "addCommitee(address)"(
      commitee: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    changeRequirement(
      _required: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "changeRequirement(uint256)"(
      _required: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    commitees(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "commitees(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    confirmTransaction(
      transactionId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "confirmTransaction(uint256)"(
      transactionId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    confirmations(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "confirmations(uint256,address)"(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getCommitees(overrides?: CallOverrides): Promise<BigNumber>;

    "getCommitees()"(overrides?: CallOverrides): Promise<BigNumber>;

    getConfirmationCount(
      transactionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getConfirmationCount(uint256)"(
      transactionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getConfirmations(
      transactionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getConfirmations(uint256)"(
      transactionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isCommitee(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "isCommitee(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isConfirmed(
      transactionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "isConfirmed(uint256)"(
      transactionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    removeCommitee(commitee: string, overrides?: Overrides): Promise<BigNumber>;

    "removeCommitee(address)"(
      commitee: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    replaceCommitee(
      commitee: string,
      newCommitee: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "replaceCommitee(address,address)"(
      commitee: string,
      newCommitee: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    required(overrides?: CallOverrides): Promise<BigNumber>;

    "required()"(overrides?: CallOverrides): Promise<BigNumber>;

    revokeConfirmation(
      transactionId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "revokeConfirmation(uint256)"(
      transactionId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    submitTransaction(
      destination: string,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "submitTransaction(address,bytes)"(
      destination: string,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    transactionCount(overrides?: CallOverrides): Promise<BigNumber>;

    "transactionCount()"(overrides?: CallOverrides): Promise<BigNumber>;

    transactions(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "transactions(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    MAX_COMMITEE_COUNT(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "MAX_COMMITEE_COUNT()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    addCommitee(
      commitee: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "addCommitee(address)"(
      commitee: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    changeRequirement(
      _required: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "changeRequirement(uint256)"(
      _required: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    commitees(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "commitees(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    confirmTransaction(
      transactionId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "confirmTransaction(uint256)"(
      transactionId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    confirmations(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "confirmations(uint256,address)"(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCommitees(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getCommitees()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getConfirmationCount(
      transactionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getConfirmationCount(uint256)"(
      transactionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getConfirmations(
      transactionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getConfirmations(uint256)"(
      transactionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isCommitee(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "isCommitee(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isConfirmed(
      transactionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "isConfirmed(uint256)"(
      transactionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    removeCommitee(
      commitee: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "removeCommitee(address)"(
      commitee: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    replaceCommitee(
      commitee: string,
      newCommitee: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "replaceCommitee(address,address)"(
      commitee: string,
      newCommitee: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    required(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "required()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    revokeConfirmation(
      transactionId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "revokeConfirmation(uint256)"(
      transactionId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    submitTransaction(
      destination: string,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "submitTransaction(address,bytes)"(
      destination: string,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    transactionCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "transactionCount()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transactions(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "transactions(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
